# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    name: MSlaptoppool
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-azure-blob-upload'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
   # inlineScript: 'az account show'
    inlineScript: 'az storage blob upload --account-name asadocs1  --container-name docs --name docs.html --file "docs.html" --overwrite'